-- Supabase Schema for IoT Guardian
-- Version: 2.0
-- Description: This script sets up all necessary tables, functions, and policies.
-- It includes a fix for the "infinite recursion" error by using a helper function for role checks.

-- 1. HELPER FUNCTION
-- Creates a function to safely get the role of the current user.
-- This avoids subqueries on the 'users' table within its own policies.
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE plpgsql
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN 'anon';
  ELSE
    RETURN (
      SELECT role FROM public.users WHERE id = auth.uid()
    );
  END IF;
END;
$$;


-- 2. TABLE DEFINITIONS & ROW LEVEL SECURITY (RLS)

-- USERS Table
-- Stores user profile information.
CREATE TABLE IF NOT EXISTS public.users (
    id uuid NOT NULL PRIMARY KEY, -- Corresponds to auth.users.id
    first_name character varying,
    last_name character varying,
    email character varying,
    whatsapp_number character varying,
    company_name character varying,
    subscription character varying DEFAULT 'None'::character varying,
    allowed_devices integer DEFAULT 0,
    joined_date timestamp with time zone DEFAULT now(),
    avatar_url character varying,
    role character varying DEFAULT 'user'::character varying,
    allow_bluetooth_control boolean DEFAULT false,
    allow_water_leak_config boolean DEFAULT false,
    subscription_expiry_date timestamp with time zone,
    CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);
-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;


-- DEVICES Table
-- Stores the latest status and information for each IoT device.
CREATE TABLE IF NOT EXISTS public.devices (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    device_id character varying NOT NULL UNIQUE,
    name character varying,
    owner uuid, -- Changed to uuid to reference users.id
    status character varying, -- e.g., 'online', 'offline', 'warning'
    last_seen timestamp with time zone,
    type character varying,
    temperature double precision,
    humidity double precision,
    water_leak boolean,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT devices_owner_fkey FOREIGN KEY (owner) REFERENCES public.users(id) ON DELETE SET NULL
);
-- Enable RLS
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;


-- SENSOR_DATA Table
-- Stores historical sensor readings.
CREATE TABLE IF NOT EXISTS public.sensor_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    device_id character varying,
    temperature double precision,
    humidity double precision,
    water_leak boolean,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT sensor_data_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id) ON DELETE CASCADE
);
-- Enable RLS
ALTER TABLE public.sensor_data ENABLE ROW LEVEL SECURITY;


-- ISSUES Table
-- Stores common troubleshooting guides.
CREATE TABLE IF NOT EXISTS public.issues (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    title character varying,
    description text,
    image_url character varying,
    potential_causes text[],
    solutions text[],
    created_at timestamp with time zone DEFAULT now()
);
-- Enable RLS
ALTER TABLE public.issues ENABLE ROW LEVEL SECURITY;


-- DEVICE_COMMANDS Table
-- Stores commands to be sent to devices.
CREATE TABLE IF NOT EXISTS public.device_commands (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    device_id character varying NOT NULL UNIQUE,
    command character varying,
    parameters jsonb,
    timestamp timestamp with time zone,
    processed boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT device_commands_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id) ON DELETE CASCADE
);
-- Enable RLS
ALTER TABLE public.device_commands ENABLE ROW LEVEL SECURITY;


-- ERROR_REPORTS Table
-- For logging application errors.
CREATE TABLE IF NOT EXISTS public.error_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    message text,
    stack_trace text,
    digest text,
    user_id text,
    path text,
    user_agent text,
    created_at timestamp with time zone DEFAULT now()
);
-- Enable RLS
ALTER TABLE public.error_reports ENABLE ROW LEVEL SECURITY;


-- 3. SECURITY POLICIES

-- Policies for USERS table
DROP POLICY IF EXISTS "Allow authenticated users to read their own data" ON public.users;
CREATE POLICY "Allow authenticated users to read their own data" ON public.users FOR SELECT TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow admin users to read all user data" ON public.users;
CREATE POLICY "Allow admin users to read all user data" ON public.users FOR SELECT TO authenticated USING (public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "Allow users to update their own data" ON public.users;
CREATE POLICY "Allow users to update their own data" ON public.users FOR UPDATE TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow admin users to update any user data" ON public.users;
CREATE POLICY "Allow admin users to update any user data" ON public.users FOR UPDATE TO authenticated USING (public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "Allow admin users to delete any user" ON public.users;
CREATE POLICY "Allow admin users to delete any user" ON public.users FOR DELETE TO authenticated USING (public.get_user_role() = 'admin');

-- Policies for DEVICES table
DROP POLICY IF EXISTS "Allow authenticated users to read all devices" ON public.devices;
CREATE POLICY "Allow authenticated users to read all devices" ON public.devices FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow service_role to upsert device data" ON public.devices;
-- Note: This is a permissive policy for IoT devices.
CREATE POLICY "Allow service_role to upsert device data" ON public.devices FOR ALL USING (true) WITH CHECK (true);


-- Policies for SENSOR_DATA table
DROP POLICY IF EXISTS "Allow authenticated users to read sensor data" ON public.sensor_data;
CREATE POLICY "Allow authenticated users to read sensor data" ON public.sensor_data FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow service_role to insert sensor data" ON public.sensor_data;
CREATE POLICY "Allow service_role to insert sensor data" ON public.sensor_data FOR INSERT WITH CHECK (true);


-- Policies for ISSUES table
DROP POLICY IF EXISTS "Allow anyone to read issues" ON public.issues;
CREATE POLICY "Allow anyone to read issues" ON public.issues FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin to manage issues" ON public.issues;
CREATE POLICY "Allow admin to manage issues" ON public.issues FOR ALL TO authenticated USING (public.get_user_role() = 'admin');


-- Policies for DEVICE_COMMANDS table
DROP POLICY IF EXISTS "Allow any service to read commands" ON public.device_commands;
CREATE POLICY "Allow any service to read commands" ON public.device_commands FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to write commands" ON public.device_commands;
CREATE POLICY "Allow authenticated users to write commands" ON public.device_commands FOR ALL TO authenticated USING (true);


-- Policies for ERROR_REPORTS table
DROP POLICY IF EXISTS "Allow anyone to create error reports" ON public.error_reports;
CREATE POLICY "Allow anyone to create error reports" ON public.error_reports FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin to read error reports" ON public.error_reports;
CREATE POLICY "Allow admin to read error reports" ON public.error_reports FOR SELECT TO authenticated USING (public.get_user_role() = 'admin');


-- 4. DATABASE TRIGGERS

-- Function to automatically create a user profile when a new user signs up in Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, first_name, last_name, avatar_url, company_name, whatsapp_number)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'company_name',
    new.raw_user_meta_data->>'whatsapp_number'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger to avoid conflicts
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Trigger to call the function when a new user is created.
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Grant usage on the function to the postgres role
GRANT EXECUTE ON FUNCTION public.get_user_role() TO postgres;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO postgres;
```